url: https://www.mapbox.com
api: https://www.mapbox.com/core
tileApi: https://api.mapbox.com
env: production
source: docs
permalink: /:categories/:title/
baseurl: /mapbox.js
mapboxjs: v3.1.1
defaultid: 'mapbox.streets'
exclude: [dist]
future: true
accessToken: pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejh2N21nMzAxMmQzMnA5emRyN2lucW0ifQ.jSE-g2vsn48Ry928pqylcg
