api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /:categories/:title
baseurl: /mapbox.js
pygments: true
version: v1.4.0
masterbranch: master
oldversion: v0.6.7
title: mapbox.js
description: MapBox JavaScript API
rdiscount:
  extensions: [smart]
