url: https://122e4e-mapbox.global.ssl.fastly.net
api: https://122e4e-mapbox.global.ssl.fastly.net
tileApi: https://api-maps-staging.tilestream.net
accessToken: pk.eyJ1IjoibWFwYm94IiwiYSI6IlhHVkZmaW8ifQ.xZAqdcP-Qiv0PaMCmw6LoA
source: docs
permalink: /:categories/:title
baseurl: /mapbox.js
highlighter: pygments
mapboxjs: v2.1.2
mapboxjsbase: /mapbox.js/dist
defaultid: 'examples.map-i86nkdio'
rdiscount:
  extensions: [smart]
