permalink: /:categories/:title
baseurl: /mapbox.js
pygments: true
version: v1.3.1
oldversion: v0.6.7
url: https://www.mapbox.com
title: mapbox.js
description: MapBox JavaScript API
rdiscount:
  extensions: [smart]
