url: https://122e4e-mapbox.global.ssl.fastly.net
api: https://122e4e-mapbox.global.ssl.fastly.net/core
tileApi: https://api-maps-staging.tilestream.net
env: staging
source: docs
permalink: /:categories/:title/
baseurl: /mapbox.js
mapboxjs: v3.1.1
defaultid: 'mapbox.streets'
exclude: [dist]
future: true
